nginx 도커파일 수정

diff --git a/nginx/Dockerfile b/nginx/Dockerfile
--- a/nginx/Dockerfile
+++ b/nginx/Dockerfile
@@ -1,30 +1,37 @@
 FROM nginx:latest
 
-# 필요한 빌드 도구 설치
+# Install build dependencies
 RUN apt-get update && apt-get install -y wget build-essential libpcre3 libpcre3-dev zlib1g zlib1g-dev libssl-dev git
 
-# Nginx 소스 코드 다운로드
-RUN wget http://nginx.org/download/nginx-$(nginx -v 2>&1 | sed 's/^nginx version: nginx\///').tar.gz && \
-    tar -zxvf nginx-*.tar.gz && \
-    rm nginx-*.tar.gz
+# Get Nginx version
+RUN NGINX_VERSION=$(nginx -v 2>&1 | sed 's/^nginx version: nginx\///')
 
-# nginx_upstream_check_module 다운로드
+# Download Nginx source code
+RUN wget http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz && \
+    tar -zxvf nginx-${NGINX_VERSION}.tar.gz && \
+    rm nginx-${NGINX_VERSION}.tar.gz
+
+# Clone nginx_upstream_check_module
 RUN git clone https://github.com/yaoweibin/nginx_upstream_check_module.git
 
-# Nginx 재컴파일
-RUN cd nginx-* && \
+# Compile Nginx with the module
+RUN cd nginx-${NGINX_VERSION} && \
     patch -p1 < ../nginx_upstream_check_module/check_1.20.1+.patch && \
     ./configure --with-compat --add-dynamic-module=../nginx_upstream_check_module && \
-    make modules
+    make modules && \
+    if [ ! -f objs/ngx_http_upstream_check_module.so ]; then \
+        echo "Module compilation failed" && exit 1; \
+    fi
 
-# 컴파일된 모듈을 Nginx 모듈 디렉토리로 복사
-RUN cp nginx-*/objs/ngx_http_upstream_check_module.so /etc/nginx/modules/
+# Copy the compiled module to Nginx modules directory
+RUN mkdir -p /etc/nginx/modules && \
+    cp nginx-${NGINX_VERSION}/objs/ngx_http_upstream_check_module.so /etc/nginx/modules/
 
-# 불필요한 파일 삭제
-RUN rm -rf nginx-* nginx_upstream_check_module
+# Clean up
+RUN rm -rf nginx-${NGINX_VERSION} nginx_upstream_check_module
 
-# Nginx 설정 파일에 모듈 로드 지시어 추가
+# Add module loading to Nginx configuration
 RUN echo "load_module modules/ngx_http_upstream_check_module.so;" > /etc/nginx/modules-enabled/50-mod-http-upstream-check.conf
 
-# 기본 CMD 유지
+# Keep the default CMD
 CMD ["nginx", "-g", "daemon off;"]
